environment:
  matrix:
  - TARGET: 1.13.0-x86_64-pc-windows-msvc
  - TARGET: 1.13.0-x86_64-pc-windows-gnu
  - TARGET: beta-x86_64-pc-windows-msvc
  - TARGET: beta-x86_64-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe"
  - rust-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose

cache:
  - C:\Users\appveyor\.cargo
